name: text_summarization_with_T5ForConditionalGeneration
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch==2.5
      - pytorch-lightning==2.5
      - transformers==4.47
      - datasets==3.2
      - evaluate==0.4
      - rouge-score==0.1
      - ipywidgets
      - sentencepiece